def main():
    # other code...
    # line 160
    result = await mcp.call_tool(name, args)
    content_list = result if isinstance(result, list) else getattr(result, 'content', [result])
    # other code...